[build]
  command = "npm run build"
  publish  = "dist"

[functions]
  directory    = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20.18.1"

# 1) API routes -> serverless functions (put this FIRST)
[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/:splat"
  status = 200
  force  = true

# 2) SPA fallback for Vite (put this AFTER the API rule)
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
