[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

# SPA fallback for Vite
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes -> serverless functions
[[redirects]]
  from = "/api/checkout"
  to = "/.netlify/functions/checkout"
  status = 200

[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200